project_id = "mcxqqwguapdhtgawgace"

[functions.send-quote-email]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.process-expired-announcements]
verify_jwt = false

[functions.notify-new-bid]
verify_jwt = false
